Deploy app
cjdufault/lmn pull request #19
Opened 2020-11-12 20:29 UTC by cjdufault

@yp0975eu @NateBigStone @ashley7295 @sunnycake 
[Deployed app to Google App Engine](https://lmnop-295416.uc.r.appspot.com/)

2020-11-12 20:53 UTC, yp0975eu commented
This commit history shows the Postgress DB password: https://github.com/cjdufault/lmn/pull/19/commits/755e8c78394882f0a4593b7cf938c454ae93f85c

Also, it looks like nothing has changed in models.py, but it is showing newlines. Do you know what happened here? https://github.com/cjdufault/lmn/pull/19/files#diff-dcfeaa5ac3dffd54264034760914588d92fc7395c81eaa9274715840dc28100b

2020-11-12 21:51 UTC, yp0975eu commented on app.yaml
> +  POSTGRE_PW: iKlF9eCqJpILnHbE
This commit history shows the Postgress DB password :(

2020-11-12 21:52 UTC, yp0975eu requested changes
Can you clean up the commit history? Maybe rebase the commits so that it doesn't show the DB PW.

2020-11-13 04:48 UTC, NateBigStone commented on app.yaml
> +  POSTGRE_PW: iKlF9eCqJpILnHbE
It could be more trouble than it's worth to delete branches/ squash/ rebase/ chop off heads/ etc. Maybe just change the pw?

2020-11-13 07:19 UTC, cjdufault commented
Sorry about that, that was sloppy of me. I changed the db password.

2020-11-14 15:15 UTC, yp0975eu approved these changes

2020-11-15 04:08 UTC, NateBigStone approved these changes

2020-11-16 06:44 UTC, merged