add goodbye message when user logs out
cjdufault/lmn pull request #24
Opened 2020-11-23 16:24 UTC by cjdufault

@yp0975eu @NateBigStone @ashley7295 @sunnycake 
Added a "goodbye" message that is displayed when a user logs out.
Closes #8

2020-11-25 00:03 UTC, NateBigStone requested changes

2020-11-25 00:03 UTC, NateBigStone commented on lmn/views/views_users.py
> +    return render(request, 'registration/logout.html', { 'username': username })
This file doesn't seem to exist

2020-11-25 00:03 UTC, NateBigStone commented on lmn/views/views_users.py
> +    return render(request, 'registration/logout.html', { 'username': username })
django.template.exceptions.TemplateDoesNotExist: registration/logout.html

2020-11-25 04:37 UTC, yp0975eu commented
This needs some sort of test and it should be good to go.

2020-11-25 17:00 UTC, cjdufault commented on lmn/views/views_users.py
> +    return render(request, 'registration/logout.html', { 'username': username })
Sorry, I had that locally and forgot to add it.

2020-11-25 19:17 UTC, yp0975eu requested changes
For some reason `views_notes.py` and `base_styles.css` are being overwritten. Can you clean up the pull request to only have actual changes?

2020-11-26 15:48 UTC, cjdufault commented
@yp0975eu I'm not sure what happened there, but the versions of both those files in both branches are identical. It won't actually make any changes when merged.

2020-11-27 18:37 UTC, yp0975eu commented
It will make changes. It will overwrite the file's history showing this commit as it's origin and that is not entirely true.

2020-11-27 19:09 UTC, NateBigStone approved these changes

2020-11-28 14:10 UTC, cjdufault commented
@yp0975eu I'm not totally sure how to go about doing that. Could you explain it? Frankly, it seems like delving into a mess when there isn't a real problem (this won't change a single line of code), but if you can explain what you want done, I'll do it.

2020-11-28 18:13 UTC, yp0975eu commented
Please `$git rm /views/views_notes.py`

2020-11-28 18:14 UTC, yp0975eu commented
Also, please `$git rm static/css/base_style.css`.

2020-11-29 16:45 UTC, yp0975eu requested changes
This appears to be changing the directory structure.  

lmn/static/css/base_style.css → static/css/base_style.css
lmn/views/views_notes.py → views/views_notes.py

2020-11-29 16:57 UTC, yp0975eu commented on views/views_notes.py
> +    notes = Note.objects.all().order_by('-posted_date')[:20]   # the 20 most recent notes
Where did this come from?

2020-11-29 16:58 UTC, yp0975eu commented on static/css/base_style.css
> -  font-weight: bold;
Are these supposed to gone?

2020-11-29 17:25 UTC, cjdufault commented on views/views_notes.py
> +    notes = Note.objects.all().order_by('-posted_date')[:20]   # the 20 most recent notes
No idea, I didn't do that.

2020-11-29 17:26 UTC, cjdufault commented on static/css/base_style.css
> -  font-weight: bold;
I didn't touch this file.

2020-11-29 17:48 UTC, NateBigStone commented on views/views_notes.py
> +    notes = Note.objects.all().order_by('-posted_date')[:20]   # the 20 most recent notes
@yp0975eu maybe @cjdufault 's remote fetch is clara's repo?

https://github.com/claraj/lmn/blame/master/lmn/views/views_notes.py#L33

2020-11-29 17:58 UTC, yp0975eu commented on views/views_notes.py
> +    notes = Note.objects.all().order_by('-posted_date')[:20]   # the 20 most recent notes
@NateBigStone , That would explain it.

2020-11-29 18:08 UTC, NateBigStone commented on views/views_notes.py
> +    notes = Note.objects.all().order_by('-posted_date')[:20]   # the 20 most recent notes
@cjdufault what does `git remote -v` show?

2020-11-29 19:37 UTC, NateBigStone commented on views/views_notes.py
> +    notes = Note.objects.all().order_by('-posted_date')[:20]   # the 20 most recent notes
Regardless, I think this file is how it ought to be.

2020-11-30 16:00 UTC, closed without merging