created rating for user shows
cjdufault/lmn pull request #25
Opened 2020-11-23 22:40 UTC by sunnycake

@yp0975eu @NateBigStone @ashley7295 @cjdufault Please review and see if it's satisfactory enough. Thank you!

2020-11-24 14:04 UTC, claraj commented
model changes make sense to me although I haven't run the code. Missing unit tests. Modify the ones that test adding notes, and add a new test to ensure note ratings must be one of the 5 valid values. thanks!

2020-11-25 00:25 UTC, NateBigStone approved these changes

2020-11-25 00:33 UTC, NateBigStone commented on lmn/models.py
> +    rating = models.IntegerField(choices=STAR_RATING, blank=True, default=None)
rating = models.IntegerField(choices=STAR_RATING, blank=False, default=5)

2020-11-25 04:35 UTC, yp0975eu commented
This needs tests then it should be good to go.

2020-11-25 19:20 UTC, yp0975eu reviewed
Still needs tests

2020-11-25 19:22 UTC, yp0975eu requested changes
Still needs tests before merging

2020-11-27 22:34 UTC, ashley7295 requested changes
Its looking good, once it contains tests we can get it approved!

2020-11-28 05:45 UTC, sunnycake reviewed
@yp0975eu @NateBigStone @ashley7295 I've added unit tests. Let me know if there's anything else I'm missing. I've also updated the time in test_views.py. I was getting assertion error about time 11/27/2020 != 11/28/2020 so I updated that to utc and all tests have passed so far.

2020-11-28 22:29 UTC, yp0975eu approved these changes

2020-11-28 22:30 UTC, yp0975eu approved these changes
:) tests pass. Ratings are working.

2020-11-29 19:18 UTC, NateBigStone approved these changes

2020-11-29 19:23 UTC, NateBigStone commented
@sunnycake Sorry, I merged my branch in, and now there's a conflict in lmn/tests/test_forms.py I can push a fix if you can't get to it today

2020-11-29 19:33 UTC, sunnycake commented
> @sunnycake Sorry, I merged my branch in, and now there's a conflict in lmn/tests/test_forms.py I can push a fix if you can't get to it today

I'm not sure exactly where the error is. Mind point me to where you're getting the error? Thanks.

2020-11-29 19:52 UTC, yp0975eu requested changes
Just this missing assertion and this should be all set.

2020-11-29 19:52 UTC, yp0975eu commented on lmn/tests/test_forms.py
This is missing an assertion

2020-11-29 20:00 UTC, yp0975eu approved these changes

2020-11-29 20:00 UTC, yp0975eu commented
I think this is good to go :)

2020-11-29 20:01 UTC, sunnycake commented on lmn/tests/test_forms.py
Sorry about that. Thanks for the catch. I've added assertion.

2020-11-29 20:10 UTC, merged