User profile
cjdufault/lmn pull request #30
Opened 2020-11-25 01:24 UTC by yp0975eu

This PR still needs unit tests. Feel free to have a look and make suggestions while unit tests are being written.

2020-11-25 19:10 UTC, yp0975eu commented
I think we are ready for a proper review #11

2020-11-29 20:14 UTC, NateBigStone requested changes

2020-11-29 20:14 UTC, NateBigStone commented on lmn/views/views_users.py
> +    form = ProfileForm(instance=user.profile)
Should be doing a check here if user has no profile and load a blank form

2020-11-29 20:14 UTC, NateBigStone commented on lmn/views/views_users.py
> +
Is there a link to this 'edit profile' page?

2020-11-29 20:22 UTC, yp0975eu commented on lmn/views/views_users.py
> +    form = ProfileForm(instance=user.profile)
Every user has a profile. It does load a blank form if there is no data.
![Screen Shot 2020-11-29 at 2 21 31 PM](https://user-images.githubusercontent.com/17325439/100552696-4fa54080-324e-11eb-9283-3ae27d96616b.png)

2020-11-29 21:25 UTC, yp0975eu commented on lmn/views/views_users.py
> +
Yes, See base.html

2020-11-29 21:49 UTC, NateBigStone approved these changes
👍

2020-11-29 23:07 UTC, merged