Issue5 - User can add a photo to a note
cjdufault/lmn pull request #34
Opened 2020-11-27 20:02 UTC by ashley7295

This contains code from the rating branch as well but all is working and looking good! Feedback is greatly appreciated for how to improve this feature!

@yp0975eu @NateBigStone @sunnycake @cjdufault @7ibakana

2020-11-27 21:37 UTC, yp0975eu requested changes
this branch contains code for the Ratings issue #13  that has not been approved for merging yet - it still doesn't have unit tests. If the code for issue #5 can be separated from issue #13, then this PR can be reviewed independently, otherwise this will need to wait until #5 is buttoned up.

2020-11-28 06:17 UTC, sunnycake commented
As of right now, I do not see option to add photo when running the branch. Everything did run ok with no errors. I will review again after comments mentioned by @yp0975eu above is resolved.

2020-12-05 04:31 UTC, ashley7295 commented
button is included in the form, works in admin console, please check if photo can be added from form.

2020-12-05 15:44 UTC, yp0975eu commented
As you've said it works in the admin portal but for the form it doesn't appear to be working.

2020-12-07 19:03 UTC, yp0975eu requested changes
This is good to go with the exception that the default for `rating` should be set to `5` instead of `None`

2020-12-07 19:03 UTC, yp0975eu commented on lmn/models.py
> +    rating = models.IntegerField(choices=STAR_RATING, blank=True, default=None)
I think this might be a mistake. Default should be set to 5

2020-12-07 19:03 UTC, yp0975eu commented on lmn/migrations/0005_auto_20201127_1731.py
> +            field=models.IntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=None),
default should be set to 5 like `lmn/migrations/0003_auto_20201127_1708.py`

2020-12-07 19:17 UTC, ashley7295 commented on lmn/models.py
> +    rating = models.IntegerField(choices=STAR_RATING, blank=True, default=None)
wouldn't the default be None because the rating of a note is None until it is set by the user?

2020-12-07 20:54 UTC, yp0975eu commented on lmn/models.py
> +    rating = models.IntegerField(choices=STAR_RATING, blank=True, default=None)
Yes that makes sense logically, but the db and templates do not account for ratings that aren't integers. When nothing is selected, the app breaks with an error `'' is not an integer`. Setting default to 5 forces an integer. I think this can be fixed in a new issue. This PR is good to merge.

2020-12-07 20:55 UTC, yp0975eu approved these changes

2020-12-07 22:58 UTC, NateBigStone approved these changes

2020-12-08 14:14 UTC, merged