add logout page -- new, clean PR
cjdufault/lmn pull request #40
Opened 2020-11-30 16:01 UTC by cjdufault

@yp0975eu @NateBigStone @ashley7295 @sunnycake 
Closes #24

2020-11-30 16:04 UTC, yp0975eu requested changes
Looks like this may still be behind master branch.

2020-11-30 16:04 UTC, yp0975eu commented on lmn/templates/lmn/base.html
> +  <span id='welcome-user-msg'>You are logged in, <a href="{% url 'user_profile' user_pk=user.pk %}">{{ user.username }}</a>.  <a id="logout"  href="{% url 'logout' %}">Logout</a></span>
do you have the master branch merged into this branch? 'my_user_profile' is the correct url for this line

2020-11-30 17:44 UTC, cjdufault commented on lmn/templates/lmn/base.html
> +  <span id='welcome-user-msg'>You are logged in, <a href="{% url 'user_profile' user_pk=user.pk %}">{{ user.username }}</a>.  <a id="logout"  href="{% url 'logout' %}">Logout</a></span>
Oh, you know, I copied that from the other branch, and didn't check if it was up do date. I'll make that change.

2020-11-30 17:45 UTC, cjdufault commented on lmn/templates/lmn/base.html
> +  <span id='welcome-user-msg'>You are logged in, <a href="{% url 'user_profile' user_pk=user.pk %}">{{ user.username }}</a>.  <a id="logout"  href="{% url 'logout' %}">Logout</a></span>
Done.

2020-11-30 22:41 UTC, yp0975eu approved these changes

2020-12-01 03:45 UTC, NateBigStone approved these changes

2020-12-01 08:59 UTC, sunnycake commented
An operational error when clicking on user profile, but successfully logged out with message!

2020-12-01 16:49 UTC, cjdufault commented
@sunnycake I'm not getting that error, can you post the stack trace?

2020-12-01 17:56 UTC, NateBigStone commented
@cjdufault @sunnycake You may need to makemigration / migrate to get the new profile table ?

2020-12-01 20:37 UTC, merged